"""add recipients, verification, fingerprint, source health, tracking

Revision ID: e910c06f7ae1
Revises: 834de59775d8
Create Date: 2026-04-18 19:22:56.615118+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e910c06f7ae1'
down_revision: Union[str, None] = '834de59775d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_verification_tokens',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_email_verification_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_verification_tokens'))
    )
    op.create_index(op.f('ix_email_verification_tokens_token_hash'), 'email_verification_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_email_verification_tokens_user_id'), 'email_verification_tokens', ['user_id'], unique=False)
    op.create_table('digest_recipients',
    sa.Column('digest_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('unsubscribe_token', sa.String(length=64), nullable=False),
    sa.Column('unsubscribed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['digest_id'], ['digests.id'], name=op.f('fk_digest_recipients_digest_id_digests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_digest_recipients')),
    sa.UniqueConstraint('digest_id', 'email', name='uq_digest_recipient')
    )
    op.create_index(op.f('ix_digest_recipients_digest_id'), 'digest_recipients', ['digest_id'], unique=False)
    op.create_index(op.f('ix_digest_recipients_unsubscribe_token'), 'digest_recipients', ['unsubscribe_token'], unique=True)
    op.add_column('digest_deliveries', sa.Column('open_count', sa.Integer(), nullable=False))
    op.add_column('digest_deliveries', sa.Column('click_count', sa.Integer(), nullable=False))
    op.add_column('digest_deliveries', sa.Column('tracking_token', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_digest_deliveries_tracking_token'), 'digest_deliveries', ['tracking_token'], unique=True)
    op.add_column('digest_items', sa.Column('digest_id', sa.Integer(), nullable=True))
    op.add_column('digest_items', sa.Column('fingerprint', sa.String(length=64), nullable=True))
    op.add_column('digest_items', sa.Column('click_count', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_digest_items_digest_id'), 'digest_items', ['digest_id'], unique=False)
    op.create_index(op.f('ix_digest_items_fingerprint'), 'digest_items', ['fingerprint'], unique=False)
    op.create_foreign_key(op.f('fk_digest_items_digest_id_digests'), 'digest_items', 'digests', ['digest_id'], ['id'], ondelete='CASCADE')
    op.add_column('digest_sources', sa.Column('last_error', sa.Text(), nullable=True))
    op.add_column('digest_sources', sa.Column('consecutive_failures', sa.Integer(), nullable=False))
    op.add_column('digest_sources', sa.Column('health', sa.String(length=20), nullable=False))
    op.add_column('users', sa.Column('email_verified_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_verified_at')
    op.drop_column('digest_sources', 'health')
    op.drop_column('digest_sources', 'consecutive_failures')
    op.drop_column('digest_sources', 'last_error')
    op.drop_constraint(op.f('fk_digest_items_digest_id_digests'), 'digest_items', type_='foreignkey')
    op.drop_index(op.f('ix_digest_items_fingerprint'), table_name='digest_items')
    op.drop_index(op.f('ix_digest_items_digest_id'), table_name='digest_items')
    op.drop_column('digest_items', 'click_count')
    op.drop_column('digest_items', 'fingerprint')
    op.drop_column('digest_items', 'digest_id')
    op.drop_index(op.f('ix_digest_deliveries_tracking_token'), table_name='digest_deliveries')
    op.drop_column('digest_deliveries', 'tracking_token')
    op.drop_column('digest_deliveries', 'click_count')
    op.drop_column('digest_deliveries', 'open_count')
    op.drop_index(op.f('ix_digest_recipients_unsubscribe_token'), table_name='digest_recipients')
    op.drop_index(op.f('ix_digest_recipients_digest_id'), table_name='digest_recipients')
    op.drop_table('digest_recipients')
    op.drop_index(op.f('ix_email_verification_tokens_user_id'), table_name='email_verification_tokens')
    op.drop_index(op.f('ix_email_verification_tokens_token_hash'), table_name='email_verification_tokens')
    op.drop_table('email_verification_tokens')
    # ### end Alembic commands ###
